### ISSUE TITLE
Feature reqeust: support to open a directory

### ISSUE THREAD

**Issue by shafreeck** [Moeditor/Moeditor#108]
Love moeditor, it is awesome.  Do you have any plan to support to open a directory and list the files open the left sidebar ?

**Comment by Menci** [comment]
I implemented a file tree in https://github.com/Moeditor/Moeditor/blob/master/views/main/moe-treeview.js and https://github.com/Moeditor/Moeditor/blob/master/views/main/moe-path.js.

You can try uncommenting this https://github.com/Moeditor/Moeditor/blob/master/views/main/index.html#L178 and get the 'Directory' icon show in the UI.

**Comment by shafreeck** [comment]
Cool ！ Why not just open this feature ?

**Comment by shafreeck** [comment]
I did this and saw the `directory` icon indeed, but it does not work when I click on the icon. Maybe I should wait for the release version.

**Comment by blackredscarf** [comment]
@Menci @shafreeck  I click the icon but it does not work.
