### ISSUE TITLE
Bad project link on Electron blog page

### ISSUE THREAD

**Issue by capouch** [Moeditor/Moeditor#114]
I don't know if there's anything you can or want to do about this, but the blog post on the official Electron "latest apps" for August has a dead link for your project.  

[http://electron.atom.io/blog/2016/09/06/august-2016-roundup](url)

**Comment by capouch** [comment]
I just checked and the link is dead on the main Electron apps page, too:

[http://electron.atom.io/apps/](url)

**Comment by Menci** [comment]
https://github.com/Menci/moeditor.github.io/commit/6369cd506de0451ddda2e700cdfac0cebf96751c
