### ISSUE TITLE
When I export the markdown file as a pdf file, Moeditor calls the wine.

### ISSUE THREAD

**Issue by mgna17** [Moeditor/Moeditor#116]
My OS is Linux, npm version is 4.0.3, node version is v7.2.1

[This gif](https://i.imgur.com/Y1HFsqa.gif) is the whole process.(image size: 44MB)

Why dose Moeditor calls wine?

-------------------

Code in the 'moedior' script (upper left position of the gif):

```sh
#!/bin/bash

cd /usr/local/share/Moeditor
npm start
```

Code in the 'pstree.sh' script (bottom left position of the gif):

```sh
#!/bin/sh

count=0
while [[ c -lt 1000 ]]
do
   echo $[count]----------------------
   pstree -p | grep '.*\.exe'
   let count++
   sleep 1
done
```

**Comment by Menci** [comment]
Try using `xdg-open` to open a PDF file.

```
$ xdg-open test.pdf
```

Or click a PDF file in your file manager. If will invoke a default program which is set to open PDF file to open it.

Moeditor uses Electron's `shell.openItem` to open the PDF - https://github.com/Moeditor/Moeditor/blob/master/app/moe-pdf.js#L64

**Comment by mgna17** [comment]
Thank you Menci. Now I know that Moeditor will call the default program to open the exported file after exporting. And I haven't set a default pdf reader on this computer yet.
