### ISSUE TITLE
Feature Request: Open Folder & Tree-View

### ISSUE THREAD

**Issue by bdbch** [Moeditor/Moeditor#120]
I would love to have a feature which allows you to open a whole folder like Atom does so a treeview will be visible from where you can switch documents faster and don't have multiple windows open.

**Comment by Menci** [comment]
The folder tree view has been implemented half, but now I'm working on refactoring the whole project. There'll be open folder support in a future version.

**Comment by db2k** [comment]
Is there something we can help with? This would be a killer feature for me since there is no Markdown Editor that can handle my "library of notes".

**Comment by Menci** [comment]
"Library of notes"? Check for [PileMd](https://pilemd.com/)?
