### ISSUE TITLE
Writing View with hidden Markdown markup

### ISSUE THREAD

**Issue by bdbch** [Moeditor/Moeditor#121]
I used Typora before and their writing view looks like this:
https://typora.io/img/beta.mov (Video is visible as HTML5 on their website: https://typora.io/)

I really like this because you don't have to switch views to read the document without any markup. Do you think this is possible with Codemirror?

**Comment by Menci** [comment]
I call this feature 'inline preview'. I planned to support this in a very future version. Currently I have too many to do, such as code refacting ...

Maybe you can check [Abricotine](http://abricotine.brrd.fr/)
