### ISSUE TITLE
Open file in command line

### ISSUE THREAD

**Issue by egoist** [Moeditor/Moeditor#13]
This is a feature request, it would be awesome if we can make this happen, like:

```bash
$ moe readme.md
```

**Comment by Menci** [comment]
If you have installed Moeditor with `.deb`, there's already `moeditor` in `/usr/bin`.

Just

```bash
$ moeditor readme.md
```

**Comment by egoist** [comment]
Glad to know this, 👍🏻

**Comment by jeffbowen** [comment]
Possible on OS X, @Menci?

**Comment by Menci** [comment]
@jeffbowen

```
open -a Moeditor.app something.md
```

**Comment by jeffbowen** [comment]
@Menci Thanks.
