### ISSUE TITLE
**The future of Moeditor**

### ISSUE THREAD

**Issue by Menci** [Moeditor/Moeditor#153]
*Moeditor's development didn't **stop**, it just **suspended**.*

Hi, I'm the owner of this project.

As we all know, Moeditor has had no updates for a long time. I'm very sorry about that. Because I was busy on another project (syzoj/syzoj, not relative to Moeditor) and now I am busy on schoolwork. I'll have time again when I'm graduated from high school in June, 2018.

I didn't give up the development of Moeditor. I was working on a new version in a new codebase with React at the beginning of this year. This's what it looks like now.

![screenshot_20171104_170942](https://user-images.githubusercontent.com/11341955/32404131-245f63de-c185-11e7-9d27-98289ded45ab.png)

![screenshot_20171104_171000](https://user-images.githubusercontent.com/11341955/32404132-24a93856-c185-11e7-98e9-573ac947f548.png)

![screenshot_20171104_171125](https://user-images.githubusercontent.com/11341955/32404133-24dff9ae-c185-11e7-90bd-80f5c6620395.png)

I am uploading it to https://github.com/Moeditor/MoeditorNew, you can clone that and try to run. Notice that it can't open/save document and settings now.

The development will restart in serveral months. I am not sure whether I'll start another new codebase or continue on the "MoeditorNew" above.

Hope someone can check my new code and give me some advice, thanks.

**Comment by mintaka3** [comment]
前OIer来点个赞

**Comment by Jinva** [comment]
不错不错，值得期待！

**Comment by ChenZ01** [comment]
加油大大！还有，请问您的博客https://oi.men.ci用的NexT主题，侧边栏是如何整合“文章目录”与“站点概览”的呢？

**Comment by liqifei007** [comment]
点个赞, follow走起

**Comment by asmwarrior** [comment]
Good work!

**Comment by Weixd** [comment]
I think the level of development will be higher and higher when I seeing your work.

**Comment by Jerx2y** [comment]
splendid！

**Comment by Menci** [comment]
Now I can back for the developmen!  
Contact me or discuss on Telegram: https://t.me/Moeditor

**Comment by huiyifyj** [comment]
@Menci 
Do you plan to write it again in React or Vue or others?

**Comment by Menci** [comment]
@huiyifyj React most probably.(I'm also working on my another project SYZOJ, a React-based wabsite app.) And maybe I'll start from scratch instead of basing on MoeditorNew.

**Comment by LalZzy** [comment]
赞！期待[TOC]功能的加入～

**Comment by mb21** [comment]
I've also been working on something quite similar:

PanWriter – a markdown editor with pandoc integration and paginated preview

https://panwriter.com
https://github.com/mb21/panwriter

Feedback welcome!
