### ISSUE TITLE
Lists don't nest when tab-indented

### ISSUE THREAD

**Issue by selrond** [Moeditor/Moeditor#16]
This is a common feature that all markdown editors I am aware of and tried have in common.Shouldn't this be here as well?

**Comment by Menci** [comment]
For example?

**Comment by tmr232** [comment]
The feature exists in https://github.com/wereturtle/ghostwriter and is very useful.
It also exists in MS Word and similar products.

**Comment by Menci** [comment]
I can't understand what's the problem. How to reproduce that?

**Comment by selrond** [comment]
1. Create an ordered (number) or unordered (bullet) list,
2. place the type cursor in one of the lines of the list you want to nest,
3. hit <kbd>TAB</kbd> – It should nest one level inside the list you're in. <kbd>SHIFT</kbd>+<kbd>TAB</kbd> should de-nest / nest one level outside. 

Almost every text editor has this feature. (Word, Google docs, iA Writer, StackEdit...)

**Comment by Menci** [comment]
Finally I know what you mean.

A single <kbd>Tab</kbd> works properly, but <kbd>Shift</kbd> + <kbd>Tab</kbd> doesn't work.

**Comment by tmr232** [comment]
Hmm... In some cases (such as an empty list item, `1.`), I would much prefer <kbd>Tab</kbd> to call `indentMore` and not add a tab character.
