### ISSUE TITLE
Export As 

### ISSUE THREAD

**Issue by kant1** [Moeditor/Moeditor#2]
Is it possible/planned to add an PDF/HTML export or the rendering ?
It will be really usefull ;)

**Comment by buildersbrewery** [comment]
Maybe check if Multimarkdown, Pandoc, etc. are in PATH, then forward to those if applicable?

**Comment by buildersbrewery** [comment]
Compare for export options:

* https://github.com/wereturtle/ghostwriter (This one is Qt, not Electron. However functionality wise it should suffice for a first example.)

**Comment by Menci** [comment]
Now we can export as HTML since https://github.com/Moeditor/Moeditor/commit/c40ab3c2aab0d428ff2ccfb8003870caef482dff.

**Comment by Menci** [comment]
Export to PDF is not so easy. We need a tool to convert html to pdf.

**Comment by tmr232** [comment]
As mentioned by @buildersbrewery, we can require such a tool (pandoc, MultiMarkdown) to be installed, and then we need only to use it.

**Comment by Menci** [comment]
Now we can export as PDF since https://github.com/Moeditor/Moeditor/commit/bcd7423c0de8e8e848d6af36d7b30662b71aa2b3.
