### ISSUE TITLE
构建失败

### ISSUE THREAD

**Issue by maoxianfly** [Moeditor/Moeditor#22]
D:\Users\fly\Documents\GitHub\Moeditor [master]> cnpm start

> moeditor@0.0.1 start D:\Users\fly\Documents\GitHub\Moeditor
> electron .

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\Users\fly\Documents\GitHub\Moeditor\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (D:\Users\fly\Documents\GitHub\Moeditor\node_modules\electron-prebuilt\index.js:4:42)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\fly\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\fly\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://registry.npm.taobao.org" "start"
npm ERR! node v4.2.1
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! moeditor@0.0.1 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the moeditor@0.0.1 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the moeditor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs moeditor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls moeditor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Users\fly\Documents\GitHub\Moeditor\npm-debug.log

**Comment by Menci** [comment]
是不是网络问题？感觉问题在下载 Electron 的时候。

**Comment by maoxianfly** [comment]
应该不是网络问题，node_modules都下载正常，但是没有electron-prebuilt\path.txt文件

**Comment by Menci** [comment]
```bash
cnpm remove electron-prebuilt
cnpm install
```

重新试试

**Comment by maoxianfly** [comment]
重新下载就好了。但是启动的时候又报错了

TypeError: Cannot read property 'get' of undefined at new MoeditorWindow
(D:\Users\fly\Documents\GitHub\Moeditor\app\moe-window.js:34:40) at MoeditorApplicatioaopen

(D:\Users\fly\Documents\GitHub\Moeditor\app\moe-app.js:41:21) at MoeditorApplicatioarurt

(D:\Users\fly\Documents\GitHub\Moeditor\app\moe-app.js:67:36)

	at EventEmitter.<anonymous>

	(D:\Users\fly\Documents\GitHub\Moeditor\app\index.js:34:9)

	at emitOne (events.js:101:20)

at EventEmitter.emit (events.js:188:7)

**Comment by Menci** [comment]
可能那时的代码有一半忘了 commit 上去，参见 https://github.com/Moeditor/Moeditor/commit/d289e19928c9f0b9f50f3416676b42cc8b014291。

现在再试试？
