### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by lucaschimweg** [Moeditor/Moeditor#25]
What about this topic? I think it would be cool, I can build it but I just want to ask if there is interest in having something like this, even if there is not much text in the application. We could detect the OS language and set the program language with that. I could translate Moeditor to German and French.

**Comment by Menci** [comment]
Great! Although not Moeditor don't have so much texts. It'll be helpful for the coming Settings and Blogging features.

**Comment by lucaschimweg** [comment]
Okay I will do a pull request!
