### ISSUE TITLE
feature request: auto reload

### ISSUE THREAD

**Issue by searene** [Moeditor/Moeditor#29]
Feature request:

When moeditor loses the focus and gets the focus again, it should check whether the contents of the current file has changed, and if so, reload the current file to the latest version.

**Comment by Menci** [comment]
What should it do if Moeditor's content is changed, and the file on the disk is changed too?

Should it popup a prompt?

**Comment by searene** [comment]
I think the way most editors deal with this is to reload the editor automatically without a prompt, because this is what users want in most cases.

And in configurations, you can let the user control whether they want the editor to be reloaded when contents are changed. Options could be:

1. automatically reload(default)
2. prompt every time
3. don't reload

Just my two cents. Moeditor may be the most elegant markdown editor I've ever used in Linux, I hope it could be better. :)

**Comment by Menci** [comment]
OK, I'll add that options.
