### ISSUE TITLE
Narrow Zen Mode

### ISSUE THREAD

**Issue by tmr232** [Moeditor/Moeditor#36]
The current Zen mode fills the entire screen, making the lines very long.
It would be better IMO if it were narrow and centered. Otherwise it is quite hard to use on a wide screen.

**Comment by Menci** [comment]
Like [ghostwriter](https://wereturtle.github.io/ghostwriter/)?

**Comment by tmr232** [comment]
Yep.

**Comment by Wamadahama** [comment]
This should be pretty quick to add.

**Comment by tmr232** [comment]
I think so too, should be a simple change to the `.css`. But I just couldn't get it centered.

**Comment by Menci** [comment]
Now I am working on a new UI with a side menu and a icon bar in the bottom. We'll have the option for 'content width' in 'zen mode'.

**Comment by Wamadahama** [comment]
I have been trying to fiddle with the padding and margins but it causes a lot of ui inconsistencies, I will look into it more but after UI update mentioned above

**Comment by Menci** [comment]
Now I commited the new UI. My idea for zen mode is a 'eye' button in the right of the bottom bar to toggle it.

**Comment by Wamadahama** [comment]
Something like this? 

![zen-mode](https://cloud.githubusercontent.com/assets/7297073/17217788/9a55bfb0-54b3-11e6-98a1-79598acc7775.png)

**Comment by Menci** [comment]
Yes and I'll finish in several minutes.

**Comment by Menci** [comment]
See https://github.com/Moeditor/Moeditor/commit/84b2d50f3819934f919471a1df99c6eb74f446fa. The width is still not configurable now but very easy to add. Maybe tomorrow I'll add a menu for that.

**Comment by Wamadahama** [comment]
Thanks for fixing my implementation :)

Looks great

**Comment by Menci** [comment]
I added options for 'edit mode' in https://github.com/Moeditor/Moeditor/commit/bccfdeb947bad3096434de9ec3d015cbc9824887. We have wide/medium/narrow zen mode and preview mode now.

Maybe this issue can be closed now.

**Comment by tmr232** [comment]
This is great!

Personally, though, I prefer it a bit narrower, so I created  pull request with editor width matching Ghostwriter.
Additionally, I think that the scrollbar should stick to the edge of the window, and not the text boundary, as it is hard to find and use this way.

**Comment by Menci** [comment]
See this commit https://github.com/Moeditor/Moeditor/commit/cc2070a30e1b936e9d37a4f614075dc501a61ff3.
