### ISSUE TITLE
Add brew cask install support

### ISSUE THREAD

**Issue by hustcer** [Moeditor/Moeditor#4]
Thanks for the great work! 
It's better to add `brew cask install` support. That way, we can install it by:

```
brew cask install moeditor
```

**Comment by Menci** [comment]
Sorry I don't really know how to publish to Homebrew, and most time I work on Linux. If you have time and OS X, you can help me do that.

**Comment by hustcer** [comment]
I'll keep an eye on it, but don't count on me too much.

**Comment by janosorcsik** [comment]
Hello!

Please add zip versions to releases.
Brew doesn't work with 7z files.

**Comment by hustcer** [comment]
@janosorcsik  Thanks. Actually, I just know how to use it, and don't know how to create a cask. It will take time for me to learn.

**Comment by janosorcsik** [comment]
@hustcer I created the cask but it's not working with 7z :)

**Comment by hustcer** [comment]
@Menci @janosorcsik Then we have to wait for a zip version release.

**Comment by Menci** [comment]
I will add that in the next release, about one month later (since I am so busy with studying XD).

**Comment by Turbo87** [comment]
I just installed it via `brew cask install moeditor` and it works fine, so I guess this issue can be closed now.

**Comment by aexmachina** [comment]
It would be good to get the brew cask updated when a new release is made.
