### ISSUE TITLE
Add read mode

### ISSUE THREAD

**Issue by jetz** [Moeditor/Moeditor#40]
sometimes I just want to read a rendered markdown file, so can we have a read mode like zen mode?

**Comment by Menci** [comment]
Good idea.

**Comment by jetz** [comment]
@Menci  can we have this feature ?

**Comment by Menci** [comment]
Yes, soon.

**Comment by Menci** [comment]
See this commit https://github.com/Moeditor/Moeditor/commit/b56bdf8ac6e3ebf44863de5ee517043b8af5339a.
