### ISSUE TITLE
Vim key bindings

### ISSUE THREAD

**Issue by jetz** [Moeditor/Moeditor#41]
As a vimer, I think vim key bindings may be a  great feature. Add the editor seems to use codemirror, if so, [vim.js](https://codemirror.net/keymap/vim.js) may be helpful.

**Comment by Menci** [comment]
Good idea.

**Comment by Wamadahama** [comment]
I think code mirror has a  [https://codemirror.net/demo/vim.html](vim mode)

**Comment by jetz** [comment]
@Wamadahama  yes, need include keymap/vim.js, may be more work to do.
@Menci  will be this feature in the roadmap?

**Comment by Menci** [comment]
Yes, it'll be available soon.

**Comment by Menci** [comment]
Well, the vim keymap in CodeMirror is not so good. Such as it has problems with Chinese. Maybe the feature won't be added soon. Sorry.

**Comment by jetz** [comment]
That's a pity. Maybe an issue report to upstream is necessary.

**Comment by Menci** [comment]
The codemirror issue is here https://github.com/codemirror/CodeMirror/issues/3256.
