### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by kemelzaidan** [Moeditor/Moeditor#43]
Hi,

I'd like to try to contribute by adding web publishing to ghost or wordpress. How should I proceed?

Thanks and congratulations for the great app!

**Comment by Menci** [comment]
Oh, I want to add this feature but I don't have so much time.

Very welcome if you can work on it!

**Comment by Menci** [comment]
My idea is first to have a lib for a interface to access blog platforms, and implement for each platform such as WP, Ghost, Hexo.

We can have a article list view in where the file list is in now (in the latest commit, a very simple file list, not released yet). Maybe a list with excerpt like [Leanote](http://leanote.org/) is better. But don't make the UI too complex

That's my idea, feel free to talk yours.

**Comment by Menci** [comment]
Web publishing is really a big project to do. Maybe you can view the source code struct at first (Sorry I don't think my code is so good). And fork your one and commit on. Or I can also add you to the organization.

**Comment by Menci** [comment]
Close due to no reply in so long time.
