### ISSUE TITLE
how to use relative file path when inserting images

### ISSUE THREAD

**Issue by smilingsun** [Moeditor/Moeditor#44]
As far as I tried,  a file path like this would work 
```
![encoded-jwt](/home/username//technical_writing/encoded-jwt3.png)
```
but these following relative path would not: 
```
![encoded-jwt](encoded-jwt3.png)
```
or 
```
![encoded-jwt](./encoded-jwt3.png)
```

although this image file sits along with my markdown file.

Hope relative file path is supported, and thanks so much for your awesome work!

**Comment by Menci** [comment]
Maybe there's a bug -- `![encoded-jwt](./encoded-jwt3.png)` is rendered to `<img src="./encoded-jwt3.png">`, and the base uri is in the app dir.
