### ISSUE TITLE
Mode selection menu looks wrong

### ISSUE THREAD

**Issue by tmr232** [Moeditor/Moeditor#46]
![image](https://cloud.githubusercontent.com/assets/1386239/17768830/9c1633ca-653e-11e6-9a96-f45f07bcb746.png)

The line breaks make it look really odd.

**Comment by Menci** [comment]
Are you using Windows? I decreased the menu item height in a recent release, but I haven't tested it on Windows. (I don't have a windows installation)

**Comment by tmr232** [comment]
Yes, I use Windows. The issue IMO is not the height, but the width, Having line breaks in the menu is annoying.

Thanks for the quick reply :smile:

**Comment by Menci** [comment]
Oh yes it's the width. XD.

I don't have that font so I can't test it. Please open the dev tools with `Ctrl + Shift + I` and test how wide can contain the text. Thanks.
