### ISSUE TITLE
Can you please support footnote and TOC and UML diagrams

### ISSUE THREAD

**Issue by jemyzhang** [Moeditor/Moeditor#48]
check with stackedit welcome document, footnote is not support yet. can you please support it ?

And if UML diagrams can be support, that will be perfect.

**Comment by Menci** [comment]
I can add the UML diagrams supports, but what's the "footnote"?

**Comment by jemyzhang** [comment]
as explained in stackedit:

### Footnotes

You can create footnotes like this[^footnote].

  [^footnote]: Here is the *text* of the **footnote**.

**Comment by Menci** [comment]
We use a markdown parser forked from [marked](https://github.com/chjj/marked), it seems that marked doesn't support this.

Now I have no idea to add footnotes support.
