### ISSUE TITLE
Website Defekt Ubuntu Download

### ISSUE THREAD

**Issue by flofriday** [Moeditor/Moeditor#50]
This may just be a silly Bug, however I just try to install the editor over on https://moeditor.github.io/ and since I am on Ubuntu i clicked on the ubuntu Button. But instead of downloading any file i just got a github error message. (All other downloads starts just normal)

**Comment by flofriday** [comment]
Issue now on the website repo
https://github.com/Moeditor/moeditor.github.io/issues/1

**Comment by Menci** [comment]
Fixed.
