### ISSUE TITLE
Question about package.json

### ISSUE THREAD

**Issue by amilajack** [Moeditor/Moeditor#51]
I was going through the package.json and i noticed [this line](https://github.com/Moeditor/Moeditor/blob/master/package.json#L33). Is that semvar correct?

**Comment by Menci** [comment]
That package is published by me. The FUCKING NPM doesn't allow me to re-publish the same version after I published it with something wrong. I can only add a `0` to the version number each time I re-publish it.

The package is not written by me, and it's using Bower before, so I tried so many times to publish correctly.

**Comment by amilajack** [comment]
Why are you trying to publish this project with npm?

**Comment by Menci** [comment]
You mean Moeditor? Moeditor isn't published to NPM.

**Comment by amilajack** [comment]
Oh I see. You're referring to `js-sequence-diagrams`.
