### ISSUE TITLE
Question: Opening devtools?

### ISSUE THREAD

**Issue by amilajack** [Moeditor/Moeditor#52]
What is the instructed development guide for this project? I'm trying to debug the project bug I cant open devtools because they're not included. What is the recommended method of debugging?

**Comment by Menci** [comment]
1. Add `--debug` to the command line args.

    e.g.
    ```
    $ npm start -- --debug
    ```

    or

    ```
    $ node_modules/electron/dist/electron . --debug
    ```
2. Set `debug` to `true` in the config. The config file is stored in `~/.config/configstore/Moeditor.json`.
3. <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd> in Linux / Windows or <kbd>Command</kbd> + <kbd>Option</kbd> + <kbd>I</kbd> in OS X / macOS to toggle devtools for a window.

**Comment by amilajack** [comment]
Thanks!
