### ISSUE TITLE
Bug: Aboutscreen Link

### ISSUE THREAD

**Issue by flofriday** [Moeditor/Moeditor#55]
On the Aboutscreen "Menci" seems to be a link, however it doesn't open anything.

**Comment by Menci** [comment]
That's just because I haven't made a good personal page. It's NOT a link now.

Maybe it WILL be a link.

**Comment by flofriday** [comment]
Ok, if it isn't it should look diferent then the actual link. 

Btw you are awsome!
Moeditor is a nice piece of software and I am just impressed how fast you react to issues.

**Comment by Menci** [comment]
The blue color looks cool, although it isn't a link. :-)
