### ISSUE TITLE
Custom stylesheet for output

### ISSUE THREAD

**Issue by akiross** [Moeditor/Moeditor#58]
I am using Markdown in a couple of minimalist websites: authors write markdown, files are uploaded and user will read the text converted to HTML.

The process has a flaw, though: the websites have particular styles, and authors usually have to iterate one or two times before getting things as they want (usually this means fixing a couple of paragraphs, links, etc).

Having an offline markdown editor is great, but it would be even greater if I could provide the authors a template of the website, including HTML and CSS, and they could use that template in their editor to have a preview of the final result.

You could provide a standardized format for templates and a directory in the Moeditor root (or in the settings dialog) where the templates could be installed, something like:

```
Moeditor\
    templates\ 
        mySite1\
            index.html
            style.css
```

and have an "entry point" in the index.html where the rendered markdown would be placed.

Would you consider this as a possible enhancement to Moeditor?

**Comment by Menci** [comment]
I am working on the custom render themes. A theme is mainly a CSS file, and may including other files such as images.

My theme idea is, you can apply CSS styles on `#container`, and you can specify for preview or export with the class selector (For example, exported HTML should use the background image in the web, preview should use the image in the local).

I am also thinking of the custom CSS. The user can install theme or custom CSSs, only a theme can be using in a time while several custom CSSs can be applied.

**Comment by Menci** [comment]
Moeditor\
        templates\ 
            mySite1\
                index.html
                style.css

What's your `index.html` mean?

**Comment by akiross** [comment]
I thought that a template could be a bit more than a CSS or a color scheme: it could be an entire HTML page in which the markdown would be embedded.

The `index.html` is the HTML template, `style.css` is used by `index.html` (and it is, as matter of fact, optional).

**Comment by Menci** [comment]
Moeditor does *NOT* render a entire HTML page. I can't find a good way to put a HTML page in the preview panel, which means even if I support export with custom HTML template, you can't preview it.

So I don't think export with a template HTML which is other than the preview is necessary, maybe you can write a script to convert the exported HTML, or using a static site generator like [Hexo](https://hexo.io/).

**Comment by akiross** [comment]
I thought that rendering an entire HTML page could be problematic...

If I wanted to hack the preview panel, where should I start looking in the source code? Maybe I can fork the code and customize the preview ad hoc for every website that I intend to support.

Thanks anyway for your help and ideas :)

**Comment by Menci** [comment]
`#container` is the container for preview.

[moe-scroll.js](https://github.com/Moeditor/Moeditor/blob/master/views/main/moe-scroll.js) is for sync scroll.

[moe-document.js](https://github.com/Moeditor/Moeditor/blob/master/views/main/moe-document.js) is for init the document.

[moe-preview.js](https://github.com/Moeditor/Moeditor/blob/master/views/main/moe-preview.js) does the preview.

Maybe you should find `container` in your atom and look them.
