### ISSUE TITLE
Align markdown to output on synchronized scrolling

### ISSUE THREAD

**Issue by tmr232** [Moeditor/Moeditor#7]
Making the output align to the currently written text would be an awesome feature.

Other than that, love the editor. It is simple, but looks amazing.

**Comment by Menci** [comment]
The StackEdit has this feature, but I can't find its implementation in its code. It seems StackEdit use itself's editor and renderer and not easy to separate that.

Sadly, Moeditor's scrollbar is only based on percent, it's not always aligned. In fact, I really want to have this feature better, but I don't know how to implement it. Maybe I have to rewrite the markdown renderer?

**Comment by tmr232** [comment]
Maybe add line-number metadata to the rendered output, so that you can match it to the source?

**Comment by tmr232** [comment]
This seems to still be a problem. When I add large images, I can't even scroll to the end of the document.

**Comment by Menci** [comment]
I am working on another better algorithm(I haven't pushed that), but I found a bug in CodeMirror so it can't work properly.

See https://github.com/codemirror/CodeMirror/issues/4108
