### ISSUE TITLE
This can't be that hard.

### ISSUE THREAD

**Issue by zekesonxx** [Moeditor/Moeditor#76]
![ss-05-09-2016-004705](https://cloud.githubusercontent.com/assets/965509/18237685/5747cf02-7302-11e6-994a-c35c74ca89eb.png)

I don't understand how this hasn't gotten fixed. Your math markup addition to Markdown can certainly be useful, but it impedes basic use of it as text editor.

**Comment by futursolo** [comment]
Since dollar sign($) is a keyword in markdown([MathJax delimiter](http://meta.stackexchange.com/questions/263343/is-the-dollar-sign-used-for-markdown-if-yes-then-how-can-i-safely-insert-i)), you should escape it by back slash(\\).
try:
```
\$100 - \$200
```

**Comment by jetz** [comment]
@zekesonxx You can turn off  `Tex Math Expressions` in `Settings->Render`.

**Comment by zekesonxx** [comment]
@jetz What settings?

**Comment by Menci** [comment]
![Render Settings](https://cloud.githubusercontent.com/assets/11341955/18257712/d0f33776-73fa-11e6-9d6d-1da6ff98cc99.png)

Click the icon in the left-bottom of the main window, click `Settings` in the side menu, select `Render` tab.

**Comment by zekesonxx** [comment]
Aha! Finally. I can actually use this now.
