### ISSUE TITLE
Rendering Code section failed

### ISSUE THREAD

**Issue by kant1** [Moeditor/Moeditor#9]
This code break the rendering of the md file.
`
\`\`\` php
$skills = array();
$skills->append($resume->getSkills());
foreach($resume->getExperiences() as $xp)
	$skills->append($xp->getSkills());
foreach($resume->getEducations() as $ed)
	$skills->append($ed->getSkills());
foreach($resume->getProjects() as $pr)
	$skills->append($pr->getSkills());
\`\`\`
`

**Comment by Menci** [comment]
A duplicate of #5.
