### ISSUE TITLE
\tag doesn't work in tex math expressions

### ISSUE THREAD

**Issue by searene** [Moeditor/Moeditor#99]
I'm not sure if this is bug or not. But the following math expression works on mathjax but fails on moeditor

$$f(x) = x + 1 \tag 1$$

**Comment by Menci** [comment]
![screenshot from 2016-10-01 18 59 12](https://cloud.githubusercontent.com/assets/11341955/19013635/5eecb7b0-8809-11e6-9022-e3b99247ef53.png)

Is it rendering correctly?

**Comment by searene** [comment]
Yes, the picture you showed was correct. This math expression works when you download the source code and start Moeditor using `npm start`, but it fails with the release version [Moeditor-0.2.0-linux-x64.7z](https://github.com/Moeditor/Moeditor/releases/download/v0.2.0-beta/Moeditor-0.2.0-linux-x64.7z).

Here's how I reproduce the problem.

1. Download [Moeditor-0.2.0-linux-x64.7z](https://github.com/Moeditor/Moeditor/releases/download/v0.2.0-beta/Moeditor-0.2.0-linux-x64.7z).
2. Uncompress the 7z file, go to the uncompressed directory, run `./Moeditor` to start it
3. Input the math expression.

The math expression won't show up in the preview pane. Just as follows.

![screenshot](http://i.imgur.com/IB35zjW.png)

**Comment by Menci** [comment]
This was fixed in https://github.com/Moeditor/Moeditor/commit/cb5076e28644bde6a71b0572648ff8a2866a744c. Please wait for the next release!
